### 手写数字识别

In [1]:
import sklearn.datasets as datasets

In [2]:
# 主成分分析
from sklearn.decomposition import PCA

In [3]:
iris = datasets.load_iris()

X = iris['data']
y = iris['target']

X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [6]:
X.shape

(150, 4)

In [12]:
# whiten,白化操作-----归一化操作（Z-score）
pca = PCA(n_components=2,whiten = True)

pca.fit(X)

X_pca = pca.transform(X)
X_pca.shape

(150, 2)

In [20]:
X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [13]:
# ? ? ? 矩阵运算
# 求解了特征值（矩阵特征），特征向量
X_pca

array([[-1.30533786,  0.64836932],
       [-1.31993521, -0.35930856],
       [-1.40496732, -0.29424412],
       [-1.33510889, -0.64613986],
       [-1.32702321,  0.6633044 ],
       [-1.10922246,  1.50488434],
       [-1.3716775 , -0.18160462],
       [-1.27714084,  0.33166784],
       [-1.40369908, -1.17396001],
       [-1.29980851, -0.23095919],
       [-1.2191728 ,  1.30947554],
       [-1.27062918,  0.02990145],
       [-1.35493432, -0.47727214],
       [-1.5677929 , -1.03811965],
       [-1.28618899,  2.39286603],
       [-1.16037307,  2.71623681],
       [-1.2758681 ,  1.64566141],
       [-1.28791362,  0.63304684],
       [-1.06981161,  1.77184386],
       [-1.25858365,  1.04251602],
       [-1.12351854,  0.79442356],
       [-1.23704894,  0.87897239],
       [-1.56396833,  0.27093722],
       [-1.11985996,  0.20037678],
       [-1.14564495, -0.07568135],
       [-1.21903752, -0.29641102],
       [-1.20063096,  0.26582861],
       [-1.24610158,  0.74646111],
       [-1.28365251,

In [17]:
from sklearn.svm import SVC

In [18]:
svc = SVC(kernel='rbf')

svc.fit(X,y)

svc.score(X,y)

C:\Anaconda3\lib\site-packages\sklearn\svm\base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


0.9866666666666667

In [19]:
svc = SVC(kernel='rbf')

svc.fit(X_pca,y)

svc.score(X_pca,y)

C:\Anaconda3\lib\site-packages\sklearn\svm\base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


0.9666666666666667

In [23]:
# 第一步求解X平均值
# 4个属性的平均值
X_mean = X.mean(axis = 0)
X_mean

array([5.84333333, 3.05733333, 3.758     , 1.19933333])

In [24]:
# 第二步相减（特征中心化）
C = X - X_mean
C

array([[-7.43333333e-01,  4.42666667e-01, -2.35800000e+00,
        -9.99333333e-01],
       [-9.43333333e-01, -5.73333333e-02, -2.35800000e+00,
        -9.99333333e-01],
       [-1.14333333e+00,  1.42666667e-01, -2.45800000e+00,
        -9.99333333e-01],
       [-1.24333333e+00,  4.26666667e-02, -2.25800000e+00,
        -9.99333333e-01],
       [-8.43333333e-01,  5.42666667e-01, -2.35800000e+00,
        -9.99333333e-01],
       [-4.43333333e-01,  8.42666667e-01, -2.05800000e+00,
        -7.99333333e-01],
       [-1.24333333e+00,  3.42666667e-01, -2.35800000e+00,
        -8.99333333e-01],
       [-8.43333333e-01,  3.42666667e-01, -2.25800000e+00,
        -9.99333333e-01],
       [-1.44333333e+00, -1.57333333e-01, -2.35800000e+00,
        -9.99333333e-01],
       [-9.43333333e-01,  4.26666667e-02, -2.25800000e+00,
        -1.09933333e+00],
       [-4.43333333e-01,  6.42666667e-01, -2.25800000e+00,
        -9.99333333e-01],
       [-1.04333333e+00,  3.42666667e-01, -2.15800000e+00,
      

In [26]:
import numpy as np

In [28]:
# 第三步求解协方差
# Estimate a covariance matrix, given data and weights
B = np.cov(C,rowvar=False)
B

array([[ 0.68569351, -0.042434  ,  1.27431544,  0.51627069],
       [-0.042434  ,  0.18997942, -0.32965638, -0.12163937],
       [ 1.27431544, -0.32965638,  3.11627785,  1.2956094 ],
       [ 0.51627069, -0.12163937,  1.2956094 ,  0.58100626]])

In [29]:
# 第四步，求解协方差的特征值和特征向量
np.linalg.eigvals(B)

array([4.22824171, 0.24267075, 0.0782095 , 0.02383509])

In [31]:
eig,eigvector = np.linalg.eig(B)

In [33]:
X_pca

array([[-1.30533786,  0.64836932],
       [-1.31993521, -0.35930856],
       [-1.40496732, -0.29424412],
       [-1.33510889, -0.64613986],
       [-1.32702321,  0.6633044 ],
       [-1.10922246,  1.50488434],
       [-1.3716775 , -0.18160462],
       [-1.27714084,  0.33166784],
       [-1.40369908, -1.17396001],
       [-1.29980851, -0.23095919],
       [-1.2191728 ,  1.30947554],
       [-1.27062918,  0.02990145],
       [-1.35493432, -0.47727214],
       [-1.5677929 , -1.03811965],
       [-1.28618899,  2.39286603],
       [-1.16037307,  2.71623681],
       [-1.2758681 ,  1.64566141],
       [-1.28791362,  0.63304684],
       [-1.06981161,  1.77184386],
       [-1.25858365,  1.04251602],
       [-1.12351854,  0.79442356],
       [-1.23704894,  0.87897239],
       [-1.56396833,  0.27093722],
       [-1.11985996,  0.20037678],
       [-1.14564495, -0.07568135],
       [-1.21903752, -0.29641102],
       [-1.20063096,  0.26582861],
       [-1.24610158,  0.74646111],
       [-1.28365251,

In [34]:
# 第五步，将数据进行降维
# X.shape = (150,4) ---->前两个最大特征值对应特征向量对数据进行降维
ret = X.dot(eigvector[:,:2])

In [37]:
X_pca

array([[-1.30533786,  0.64836932],
       [-1.31993521, -0.35930856],
       [-1.40496732, -0.29424412],
       [-1.33510889, -0.64613986],
       [-1.32702321,  0.6633044 ],
       [-1.10922246,  1.50488434],
       [-1.3716775 , -0.18160462],
       [-1.27714084,  0.33166784],
       [-1.40369908, -1.17396001],
       [-1.29980851, -0.23095919],
       [-1.2191728 ,  1.30947554],
       [-1.27062918,  0.02990145],
       [-1.35493432, -0.47727214],
       [-1.5677929 , -1.03811965],
       [-1.28618899,  2.39286603],
       [-1.16037307,  2.71623681],
       [-1.2758681 ,  1.64566141],
       [-1.28791362,  0.63304684],
       [-1.06981161,  1.77184386],
       [-1.25858365,  1.04251602],
       [-1.12351854,  0.79442356],
       [-1.23704894,  0.87897239],
       [-1.56396833,  0.27093722],
       [-1.11985996,  0.20037678],
       [-1.14564495, -0.07568135],
       [-1.21903752, -0.29641102],
       [-1.20063096,  0.26582861],
       [-1.24610158,  0.74646111],
       [-1.28365251,

In [35]:
# 第六步，z-score归一化
(ret - ret.mean(axis = 0))/ret.std(axis = 0)

array([[-1.30971087, -0.65054141],
       [-1.32435711,  0.36051227],
       [-1.40967409,  0.29522986],
       [-1.33958163,  0.64830449],
       [-1.33146886, -0.66552653],
       [-1.11293846, -1.50992585],
       [-1.37627274,  0.18221302],
       [-1.28141939, -0.33277896],
       [-1.4084016 ,  1.17789289],
       [-1.30416299,  0.23173293],
       [-1.22325714, -1.3138624 ],
       [-1.2748859 , -0.03000162],
       [-1.35947347,  0.47887104],
       [-1.57304515,  1.04159745],
       [-1.29049784, -2.40088235],
       [-1.16426043, -2.72533645],
       [-1.28014238, -1.65117453],
       [-1.29222826, -0.6351676 ],
       [-1.07339558, -1.7777797 ],
       [-1.26280003, -1.04600854],
       [-1.12728243, -0.79708495],
       [-1.24119316, -0.88191703],
       [-1.56920777, -0.27184488],
       [-1.12361159, -0.20104806],
       [-1.14948296,  0.07593489],
       [-1.2231214 ,  0.29740403],
       [-1.20465318, -0.26671917],
       [-1.25027614, -0.74896183],
       [-1.28795287,

In [38]:
eig

array([4.22824171, 0.24267075, 0.0782095 , 0.02383509])

In [39]:
pca.explained_variance_

array([4.22824171, 0.24267075])

In [40]:
pca.explained_variance_ratio_

array([0.92461872, 0.05306648])

In [44]:
eig

array([4.22824171, 0.24267075, 0.0782095 , 0.02383509])

In [45]:
pca = PCA(n_components=0.9999,whiten=True)

pca.fit(X)

X_pca = pca.transform(X)
display(X_pca.shape,pca.explained_variance_,pca.explained_variance_ratio_)


(150, 4)

array([4.22824171, 0.24267075, 0.0782095 , 0.02383509])

array([0.92461872, 0.05306648, 0.01710261, 0.00521218])

导包，使用SVM

datasets读取数据

分割训练和预测数据train_test_split(可以放多个要分割的数据)

绘制前100个图片

创建SVC模型gamma =0.001  
训练数据

预测数据，可视化

In [46]:
# svc支持向量机，对手写数字，进行识别
import pandas as pd

In [47]:
digits = pd.read_csv('./data/digits.csv')
digits.head()

label  pixel0  pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  \
0      1       0       0       0       0       0       0       0       0   
1      0       0       0       0       0       0       0       0       0   
2      1       0       0       0       0       0       0       0       0   
3      4       0       0       0       0       0       0       0       0   
4      0       0       0       0       0       0       0       0       0   

   pixel8    ...     pixel774  pixel775  pixel776  pixel777  pixel778  \
0       0    ...            0         0         0         0         0   
1       0    ...            0         0         0         0         0   
2       0    ...            0         0         0         0         0   
3       0    ...            0         0         0         0         0   
4       0    ...            0         0         0         0         0   

   pixel779  pixel780  pixel781  pixel782  pixel783  
0         0         0         0         0         0  
1         0         0         0         0         0  
2         0         0         0         0         0  
3         0         0         0         0         0  
4         0         0         0         0         0  

[5 rows x 785 columns]

In [48]:
digits.shape

(42000, 785)

In [49]:
X = digits.iloc[:,1:]

y = digits['label']

In [50]:
# 数字的杂乱无章
y

0        1
1        0
2        1
3        4
4        0
5        0
6        7
7        3
8        5
9        3
10       8
11       9
12       1
13       3
14       3
15       1
16       2
17       0
18       7
19       5
20       8
21       6
22       2
23       0
24       2
25       3
26       6
27       9
28       9
29       7
        ..
41970    2
41971    3
41972    4
41973    4
41974    3
41975    9
41976    2
41977    4
41978    4
41979    4
41980    7
41981    2
41982    8
41983    7
41984    3
41985    3
41986    0
41987    5
41988    0
41989    5
41990    3
41991    1
41992    9
41993    6
41994    4
41995    0
41996    1
41997    7
41998    6
41999    9
Name: label, Length: 42000, dtype: int64

In [52]:
28*28

784

In [51]:
# 28*28
# 784个像素
X.shape

(42000, 784)

In [54]:
# 这个像素，对于分类有用吗？？？
X['pixel0'].unique()

array([0], dtype=int64)

In [56]:
X['pixel100'].unique()

array([  0,  51, 255, 132,  53, 150, 139, 233,  59, 178, 227, 253,  98,
       164, 191, 254, 192,  69, 206, 156,  56, 185,  86, 180,  62,  48,
       143,  29, 140,  11,  41,  22, 215, 114, 122, 184,  55,  13,  85,
       210, 216, 117,  20, 234,  45, 189, 128, 163, 245, 145,  14, 218,
       131, 226,  49,  76, 174, 165,  91,  12,  99, 228, 157, 252, 195,
        47, 240,  28, 146,   5, 118, 250, 204, 221,  27, 147, 116, 142,
        93, 160, 105,  32,   1,  68, 159, 224, 239,   2,  64,  63, 194,
       220,  97,  26,  92,   8, 113,  66,  19, 236,  96,  16,  75, 205,
       168,  15, 230,  50,   7,   3,  25, 104,  65,  84,  87, 237, 102,
       244,  60, 152, 181,  30, 249,  57, 247, 190, 136, 198, 241, 246,
       213, 208,  40, 112, 225, 153, 232, 170,  42, 251,  37, 154, 193,
       197,  24, 169, 229, 248,  17,  79, 242, 211,  88, 148, 212, 175,
       222, 202,  39,  31,  90,  81,  95, 207, 162, 129,  38,  46, 109,
       149, 138, 127, 223,  35,   6, 176, 119, 151, 115, 130, 10

In [58]:
X['pixel5'].unique()

array([0], dtype=int64)

In [ ]:
# 784个属性

In [59]:
X_train = X.iloc[:5000,:]

y_train = y[:5000]
display(X_train.shape,y_train.shape)

(5000, 784)

(5000,)

In [60]:
X_test = X.iloc[-1000:,:]
y_test = y[-1000:]

In [61]:
%%time
# 没有经过数据降维
svc = SVC(kernel='rbf')

# 小样本数据，数据量不能太大
svc.fit(X_train,y_train)

print(svc.score(X_test,y_test))

C:\Anaconda3\lib\site-packages\sklearn\svm\base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


0.127
Wall time: 1min 8s


In [63]:
# 使用PCA进行降维X_train.shape = (5000,784)

pca = PCA(n_components=0.95,whiten=True)

pca.fit(X_train)

X_train_pca = pca.transform(X_train)

X_test_pca = pca.transform(X_test)

# 原来784属性降维到149个
X_train_pca.shape

(5000, 149)

In [64]:
%%time
svc = SVC(kernel='rbf')

svc.fit(X_train_pca,y_train)

# 预测
print('经过PCA降维，准确率：',svc.score(X_test_pca,y_test))

C:\Anaconda3\lib\site-packages\sklearn\svm\base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


经过PCA降维，准确率： 0.936
Wall time: 9.57 s


In [65]:
X

pixel0  pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  pixel8  \
0           0       0       0       0       0       0       0       0       0   
1           0       0       0       0       0       0       0       0       0   
2           0       0       0       0       0       0       0       0       0   
3           0       0       0       0       0       0       0       0       0   
4           0       0       0       0       0       0       0       0       0   
5           0       0       0       0       0       0       0       0       0   
6           0       0       0       0       0       0       0       0       0   
7           0       0       0       0       0       0       0       0       0   
8           0       0       0       0       0       0       0       0       0   
9           0       0       0       0       0       0       0       0       0   
10          0       0       0       0       0       0       0       0       0   
11          0       0       0       0       0       0       0       0       0   
12          0       0       0       0       0       0       0       0       0   
13          0       0       0       0       0       0       0       0       0   
14          0       0       0       0       0       0       0       0       0   
15          0       0       0       0       0       0       0       0       0   
16          0       0       0       0       0       0       0       0       0   
17          0       0       0       0       0       0       0       0       0   
18          0       0       0       0       0       0       0       0       0   
19          0       0       0       0       0       0       0       0       0   
20          0       0       0       0       0       0       0       0       0   
21          0       0       0       0       0       0       0       0       0   
22          0       0       0       0       0       0       0       0       0   
23          0       0       0       0       0       0       0       0       0   
24          0       0       0       0       0       0       0       0       0   
25          0       0       0       0       0       0       0       0       0   
26          0       0       0       0       0       0       0       0       0   
27          0       0       0       0       0       0       0       0       0   
28          0       0       0       0       0       0       0       0       0   
29          0       0       0       0       0       0       0       0       0   
...       ...     ...     ...     ...     ...     ...     ...     ...     ...   
41970       0       0       0       0       0       0       0       0       0   
41971       0       0       0       0       0       0       0       0       0   
41972       0       0       0       0       0       0       0       0       0   
41973       0       0       0       0       0       0       0       0       0   
41974       0       0       0       0       0       0       0       0       0   
41975       0       0       0       0       0       0       0       0       0   
41976       0       0       0       0       0       0       0       0       0   
41977       0       0       0       0       0       0       0       0       0   
41978       0       0       0       0       0       0       0       0       0   
41979       0       0       0       0       0       0       0       0       0   
41980       0       0       0       0       0       0       0       0       0   
41981       0       0       0       0       0       0       0       0       0   
41982       0       0       0       0       0       0       0       0       0   
41983       0       0       0       0       0       0       0       0       0   
41984       0       0       0       0       0       0       0       0       0   
41985       0       0       0       0       0       0       0       0       0   
41986       0       0       0       0       0       0       0       0       0   
41987       0       0       0       0 