In [2]:
import numpy as np 


In [6]:
a = np.random.randint(0,10,size=(2,3))

In [8]:
a.T #转置 ，方正 长宽都相当


array([[9, 2],
       [3, 3],
       [0, 2]])

In [14]:
# np.linalg.inv(a) # 如果不是方正的话是不能推到的。
#怎么得到方正呢，
#  a *转至矩阵
b = (a.T).dot(a)
b #得到方正
#求逆矩阵
np.linalg.inv(b)  #矩阵 乘以逆矩阵，就是单位矩阵


array([[ -7.05860818e+13,   2.11758246e+14,  -2.47051286e+14],
       [  2.11758246e+14,  -6.35274737e+14,   7.41153859e+14],
       [ -2.47051286e+14,   7.41153859e+14,  -8.64679503e+14]])

In [15]:
# (y-Xw) **2 #

NameError: name 'y' is not defined

In [21]:
#2(y-Wx)*-x =0  倒数
from sklearn.linear_model import LinearRegression
X = np.linspace(0,10,20)+ np.random.randn(20)*0.4
Y = np.linspace(3,5,20) + np.random.randn(20) *0.3

In [23]:
lrg = LinearRegression(fit_intercept=True)
lrg.fit(X.reshape(-1,1),Y)


LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [25]:
w = lrg.coef_
w

array([ 0.20479003])

In [26]:
b = lrg.intercept_
b

2.914280482057741