In [17]:
import sklearn.datasets as datasets
from sklearn.neighbors import KNeighborsClassifier

In [4]:
iris = datasets.load_iris()
iris

{'DESCR': 'Iris Plants Database\n====================\n\nNotes\n-----\nData Set Characteristics:\n    :Number of Instances: 150 (50 in each of three classes)\n    :Number of Attributes: 4 numeric, predictive attributes and the class\n    :Attribute Information:\n        - sepal length in cm\n        - sepal width in cm\n        - petal length in cm\n        - petal width in cm\n        - class:\n                - Iris-Setosa\n                - Iris-Versicolour\n                - Iris-Virginica\n    :Summary Statistics:\n\n    ============== ==== ==== ======= ===== ====================\n                    Min  Max   Mean    SD   Class Correlation\n    ============== ==== ==== ======= ===== ====================\n    sepal length:   4.3  7.9   5.84   0.83    0.7826\n    sepal width:    2.0  4.4   3.05   0.43   -0.4194\n    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)\n    petal width:    0.1  2.5   1.20  0.76     0.9565  (high!)\n    ============== ==== ==== ======= ===== ==

In [6]:
#data 数据， 对应 target
x = iris['data']
y = iris['target']
display(x,y)

array([[ 5.1,  3.5,  1.4,  0.2],
       [ 4.9,  3. ,  1.4,  0.2],
       [ 4.7,  3.2,  1.3,  0.2],
       [ 4.6,  3.1,  1.5,  0.2],
       [ 5. ,  3.6,  1.4,  0.2],
       [ 5.4,  3.9,  1.7,  0.4],
       [ 4.6,  3.4,  1.4,  0.3],
       [ 5. ,  3.4,  1.5,  0.2],
       [ 4.4,  2.9,  1.4,  0.2],
       [ 4.9,  3.1,  1.5,  0.1],
       [ 5.4,  3.7,  1.5,  0.2],
       [ 4.8,  3.4,  1.6,  0.2],
       [ 4.8,  3. ,  1.4,  0.1],
       [ 4.3,  3. ,  1.1,  0.1],
       [ 5.8,  4. ,  1.2,  0.2],
       [ 5.7,  4.4,  1.5,  0.4],
       [ 5.4,  3.9,  1.3,  0.4],
       [ 5.1,  3.5,  1.4,  0.3],
       [ 5.7,  3.8,  1.7,  0.3],
       [ 5.1,  3.8,  1.5,  0.3],
       [ 5.4,  3.4,  1.7,  0.2],
       [ 5.1,  3.7,  1.5,  0.4],
       [ 4.6,  3.6,  1. ,  0.2],
       [ 5.1,  3.3,  1.7,  0.5],
       [ 4.8,  3.4,  1.9,  0.2],
       [ 5. ,  3. ,  1.6,  0.2],
       [ 5. ,  3.4,  1.6,  0.4],
       [ 5.2,  3.5,  1.5,  0.2],
       [ 5.2,  3.4,  1.4,  0.2],
       [ 4.7,  3.2,  1.6,  0.2],
       [ 4

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [12]:
import numpy as np 
index = np.arange(150)
#打乱index
np.random.shuffle(index)
index

array([104,  74,  75, 134, 114,  60,   4, 117, 121,  73,  49,  91,  33,
        77,  57,  65,   2, 149,  80,  72,  44,  99,  41, 130,  43,  27,
        54, 110, 105, 131,   8,  96,  97,  81, 137, 125,  15,  25,  90,
         7,  10,  93, 138,   9,  84,  53, 136,  95,   5, 139, 147,  45,
        30,  92,  20,  58,  35, 140, 144,  13,  86, 133,  50, 124, 135,
        31,  23, 127,  32, 106,   0,  69, 129, 126,  94,  62,  88,  67,
        17,  29, 132, 148, 118,  51,  19,  24,  28,  47, 102, 145,  63,
        21, 111, 103,  12,  85,  76, 120, 112, 128,  71,  18, 100,  38,
        56,  78,  52, 141,  48,  22,  64, 113, 146,  36, 109,  55, 108,
        34,  16, 107, 119,  61, 101,  11,  66, 142,  83,  70,   6,  14,
        39,  42,  59,  40,   3, 123,  82,   1,  79, 116, 122,  46,  87,
       143, 115,  37,  89,  98,  26,  68])

In [29]:
#打乱数据去 rins里面去取
X = x[index]
Y = y[index]
# display(X,Y)

In [28]:
# #拿一部分测试数据
# x_test = X[105:]
# y_test = y[105:]
# #拿一部分训练数据  7 ：3 比例
# x_train = x[:105]
# y_train = y[:105]

#拿一部分训练数据  7 ：3 比例
x_train = X[:105]
y_train = Y[:105]
#拿一部分测试数据
x_test = X[105:]
y_test = Y[105:]
# x_train

In [32]:
# knn = KNeighborsClassifier(n_neighbors=5)
# knn.fit(x_train,y_train)
# y_ = knn.predict(x_test)
# display(y_,y_test)
# conn = y_ ==y_test
# conn
# conn.mean()

array([1, 1, 2, 0, 0, 1, 2, 2, 0, 2, 1, 2, 0, 0, 2, 2, 1, 2, 0, 1, 2, 2, 2,
       0, 0, 0, 0, 1, 0, 0, 2, 1, 0, 1, 2, 2, 0, 1, 2, 2, 0, 1, 1, 0, 1])

array([1, 1, 2, 0, 0, 1, 2, 2, 0, 2, 1, 2, 0, 0, 2, 2, 1, 2, 0, 1, 2, 1, 1,
       0, 0, 0, 0, 1, 0, 0, 2, 1, 0, 1, 2, 2, 0, 1, 2, 2, 0, 1, 1, 0, 1])

0.9555555555555556

In [39]:
#权重 distance  ，不够精准 但是更加真实了。knn 是监督学习， knn分类，归一化。  p =1  曼哈顿距离 p=2 欧几里得距离 
knn = KNeighborsClassifier(n_neighbors=5,weights='distance',p=1)
#训练
knn.fit(x_train,y_train)
#测试
knn.score(x_test,y_test)


0.9555555555555556

In [ ]:
#看一下什么是曼哈顿，欧几里得距离。